syntax = "proto3";

package game.proto.v1;

import "google/protobuf/empty.proto";
import "game/proto/v1/game_model.proto";
import "game/proto/v1/game_images_model.proto";

option csharp_namespace = "RetroGate.Protos.Game.Proto.V1";

enum GameSource {
    GAME_SOURCE_AVAILABLE = 0;
    GAME_SOURCE_INSTALLED = 1;
}

service GameService {
	rpc Create(CreateGameRequest) returns (GameModel);
    rpc GetById(GetByIdRequest) returns (GameModel);
    rpc GetAll(GetAllRequest) returns (GetAllResponse);
    rpc FindByName(FindByNameRequest) returns (FindByNameResponse);
    rpc Update(UpdateGameRequest) returns (GameModel);
    rpc Delete(GetByIdRequest) returns (google.protobuf.Empty);
    rpc GetImages(GetImagesRequest) returns (GameImagesModel);
    rpc FindInstalledGames(google.protobuf.Empty) returns (GetAllResponse);
}

message CreateGameRequest {
    GameSource source = 1;
    GameModel game = 2;
}

message GetByIdRequest {
    GameSource source = 1;
    string id = 2;
}

message GetAllRequest {
    GameSource source = 1;
}

message GetAllResponse {
    repeated GameModel games = 1;
}

message FindByNameRequest {
    GameSource source = 1;
    string name = 2;
}

message FindByNameResponse {
    repeated GameModel games = 1;
}

message UpdateGameRequest {
    GameSource source = 1;
    GameModel game = 2;
}

message GetImagesRequest {
    string game_name = 1;
}
