syntax = "proto3";

package game.proto.v1;

import "google/protobuf/empty.proto";
import "game/proto/v1/game_model.proto";
import "game/proto/v1/game_images_model.proto";

option csharp_namespace = "RetroGate.Protos.Game.Proto.V1";

service GameService {
	rpc Create(GameModel) returns (GameModel);
    rpc GetById(GetByIdRequest) returns (GameModel);
    rpc GetAll(google.protobuf.Empty) returns (GetAllResponse);
    rpc FindByName(FindByNameRequest) returns (FindByNameResponse);
    rpc Update(GameModel) returns (GameModel);
    rpc Delete(GetByIdRequest) returns (google.protobuf.Empty);
    rpc GetImages(GetImagesRequest) returns (GameImagesModel);
}

message GetByIdRequest {
    string id = 1;
}

message GetAllResponse {
    repeated GameModel games = 1;
}

message FindByNameRequest {
    string name = 1;
}

message FindByNameResponse {
    repeated GameModel games = 1;
}

message GetImagesRequest {
    string game_name = 1;
}