<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="game\proto\v1\game_model.proto" />
    <Protobuf Include="game\proto\v1\game_images_model.proto" />
    <Protobuf Include="game\proto\v1\game_service.proto" />
    <Protobuf Include="shortcut\proto\v1\shortcut_model.proto" />
    <Protobuf Include="shortcut\proto\v1\shortcut_service.proto" />
    <Protobuf Include="installer\proto\v1\installer_model.proto" />
    <Protobuf Include="installer\proto\v1\installer_service.proto" />
    <Protobuf Include="config\proto\v1\config_model.proto" />
    <Protobuf Include="config\proto\v1\config_service.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.1" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
